/**
 * The pinyin table and the slug discipline around it.
 *
 * `assets/pinyin.json` replaces the optional `pypinyin` dependency. The asset is
 * generated by `scripts/generate-pinyin.mjs` from Unihan; here we check the
 * shipped provenance, spot-check readings, and — most importantly — that a
 * missing or incomplete table fails loudly instead of emitting a junk slug.
 */

import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import {
  SlugResolutionError,
  containsHan,
  isHanCharacter,
  loadPinyinTable,
  pinyinSyllables,
  readingToSyllable,
  resetPinyinTable,
  setSlugifyTable,
} from "../src/skill/slug.mjs";
import { slugify } from "../src/skill/writer.mjs";
import { buildAsset, parseUnihan } from "../scripts/generate-pinyin.mjs";

const projectRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const assetPath = join(projectRoot, "assets", "pinyin.json");

test("the shipped asset carries its provenance and license", () => {
  const asset = JSON.parse(readFileSync(assetPath, "utf8"));
  assert.equal(asset.source.database, "Unihan");
  assert.equal(asset.source.file, "Unihan_Readings.txt");
  assert.match(asset.license.name, /Unicode License/);
  assert.match(asset.license.url, /^https:\/\/www\.unicode\.org\//);
  assert.equal(asset.selection.limit, 3500);
  assert.equal(asset.count, Object.keys(asset.characters).length);
  assert.ok(asset.count >= 3000, `expected ~3500 characters, got ${asset.count}`);
  assert.ok(asset.selection.covered_characters >= asset.count);
  assert.equal(asset.generated_by, "scripts/generate-pinyin.mjs");
});

test("common characters map to their standard reading", () => {
  const table = loadPinyinTable();
  assert.equal(table["周"], "zhōu");
  assert.equal(table["的"], "de");
  assert.equal(table["女"], "nǚ");
  assert.equal(table["张"], "zhāng");
});

test("slugify matches pypinyin for Latin and covered Han names", () => {
  assert.equal(slugify("Zadie Smith"), "zadie-smith");
  assert.equal(slugify("Élodie"), "elodie");
  assert.equal(slugify("A/B"), "a-b");
  assert.equal(slugify("周奇墨"), "zhou-qi-mo");
  assert.equal(slugify("徐志胜"), "xu-zhi-sheng");
  assert.equal(slugify("张伟"), "zhang-wei");
});

test("ü becomes v, exactly like pypinyin", () => {
  assert.equal(readingToSyllable("lǚ"), "lv");
  assert.equal(readingToSyllable("nǚ"), "nv");
  assert.equal(readingToSyllable("zhōu"), "zhou");
});

test("an uncovered character asks for --slug instead of guessing", () => {
  // 吕 is a common surname that the frequency-selected table does not cover.
  assert.equal(loadPinyinTable()["吕"], undefined);
  assert.throws(
    () => slugify("吕丽"),
    (error) => error instanceof SlugResolutionError && /--slug/.test(error.remedy),
  );
});

test("a missing table fails for Han names but still handles Latin ones", () => {
  setSlugifyTable(null);
  try {
    assert.throws(() => slugify("周奇墨"), SlugResolutionError);
    assert.equal(slugify("Zadie Smith"), "zadie-smith");
    assert.deepEqual(pinyinSyllables("A/B"), ["A/B"]);
  } finally {
    resetPinyinTable();
  }
  assert.ok(loadPinyinTable());
});

test("Han detection covers the CJK blocks the table is built from", () => {
  assert.equal(isHanCharacter("周"), true);
  assert.equal(isHanCharacter("A"), false);
  assert.equal(containsHan("Zadie Smith"), false);
  assert.equal(containsHan("周奇墨"), true);
  assert.equal(containsHan("Élodie"), false);
});

const FIXTURE = [
  "# Unihan_Readings.txt",
  "# Date: 2025-07-24 00:00:00 GMT [KL]",
  "# Unicode Version 17.0.0",
  "U+4E00\tkHanyuPinlu\tyī(32747)",
  "U+4E00\tkMandarin\tyī",
  "U+4E8C\tkHanyuPinlu\tèr(950)",
  "U+4E8C\tkMandarin\tèr",
  "U+4E09\tkHanyuPinlu\tsān(12) sàn(3)",
  "U+4E09\tkMandarin\tsān sàn",
  "U+56DB\tkHanyuPinlu\tsì(5)",
  "",
].join("\n");

test("the generator is deterministic and prefers kMandarin", () => {
  const parsed = parseUnihan(FIXTURE);
  assert.equal(parsed.unicodeVersion, "17.0.0");
  assert.equal(parsed.frequencies.size, 4);

  const asset = buildAsset(parsed, 3);
  assert.equal(asset.count, 3);
  assert.equal(asset.selection.limit, 3);
  // Code-point order, kMandarin (first reading) wins, ties break on frequency.
  assert.deepEqual(Object.keys(asset.characters), ["一", "二", "三"]);
  assert.equal(asset.characters["三"], "sān");
  // A character without kMandarin falls back to its most frequent reading.
  const fallback = buildAsset({ ...parsed, readings: new Map() }, 4);
  assert.equal(fallback.characters["三"], "sān");
  assert.equal(fallback.characters["四"], "sì");

  // limit 0 keeps every covered character.
  assert.equal(buildAsset(parsed, 0).count, 4);
  // Same input, same bytes.
  assert.equal(JSON.stringify(buildAsset(parsed, 3)), JSON.stringify(asset));
});
